# Generated by Django 4.0 on 2022-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servivio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fructosa', models.CharField(max_length=50)),
                ('lactosa', models.CharField(max_length=50)),
                ('sorbitol', models.CharField(max_length=50)),
                ('gos', models.CharField(max_length=50)),
                ('fructano', models.CharField(max_length=50)),
                ('gr', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
    ]
